run:
  timeout: 1m

linters-settings:
  funlen:
    lines: 65
    statements: 40

linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exhaustive
    - exportloopref
    - gocognit
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    - durationcheck
    - forbidigo
    - forcetypeassert
    - ifshort
    - importas
    - nilerr
    - predeclared
    - thelper
    - tparallel
    - wastedassign
    - promlinter
    - bodyclose
    - godot
    - funlen
    - wsl
    - gocritic
    - prealloc
    - unparam
    # - nlreturn
    # - revive
    # - dupl
    # - gochecknoglobals
    # - gochecknoinits
    # - goconst
    # - godox
    # - goerr113
    # - gosec
    # - noctx
    # - stylecheck
    # - testpackage
    # - cyclop
    # - errorlint
    # - tagliatelle

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - funlen
        - gocognit