version: "3.3"

services:
  postgres:
    image: postgres:12.1
    container_name: scht-postgres_test
    environment:
      - POSTGRES_DB=scht_db_test
      - POSTGRES_USER=scht_user
      - POSTGRES_PASSWORD=scht_password
    ports:
      - "5433:5432"
    networks:
      - scht-backend-network_test

  redis:
    image: redis:6.2.5
    container_name: scht-redis_test
    ports:
      - "6380:6379"
    networks:
      - scht-backend-network_test

networks:
  scht-backend-network_test: