// Code generated by mockery v2.40.1. DO NOT EDIT.

package auth

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionStorage is an autogenerated mock type for the SessionStorage type
type MockSessionStorage struct {
	mock.Mock
}

// GetWithDelete provides a mock function with given fields: ctx, refreshToken
func (_m *MockSessionStorage) GetWithDelete(ctx context.Context, refreshToken string) (Session, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for GetWithDelete")
	}

	var r0 Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (Session, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) Session); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, sess
func (_m *MockSessionStorage) Set(ctx context.Context, sess Session) error {
	ret := _m.Called(ctx, sess)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, Session) error); ok {
		r0 = rf(ctx, sess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSessionStorage creates a new instance of MockSessionStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStorage {
	mock := &MockSessionStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
