is_debug: true
domain: localhost
listen:
  type: port
  bind_id: 127.0.0.1
  bind_port: 8000
auth:
  sign_key: qwerty
  access_token_ttl: 15      # 15 minutes
  refresh_token_ttl: 43200  # 30 days
postgres:
  host: 127.0.0.1
  port: 5432
  database: scht_db
  username: scht_user
  password: scht_password
redis:
  host: 127.0.0.1
  port: 6379
  username: default
  password: ""
logging:
  level: debug
  filepath: ./logs/all.log
  rotate: true
  max_size: 100   # MB
  max_backups: 5  # max files
cors:
  allowed_origins:
    - 127.0.0.1:3000
    - localhost:3000
  max_age: 600 # 10 minutes