is_debug: true
domain: localhost
listen:
  type: port
  bind_id: 127.0.0.1
  bind_port: 8000
auth:
  sign_key: qwerty
  access_token_ttl: 15     # 15 minutes
  refresh_token_ttl: 43200 # 30 days
postgres:
  host: 127.0.0.1
  port: 5432
  database: scht_db
  username: scht_user
  password: scht_password
redis:
  host: 127.0.0.1
  port: 6379
  username: scht_user
  password: scht_password
