is_debug: true
domain: localhost
listen:
  api:
    type: port
    bind_ip: 127.0.0.1
    bind_port: 8001
  chat:
    type: port
    bind_ip: 127.0.0.1
    bind_port: 8081
auth:
  sign_key: qwerty
  access_token_ttl: 30      # 30 minutes
  refresh_token_ttl: 43200  # 30 days
postgres:
  host: 127.0.0.1
  port: 5433
  database: scht_db_test
  username: scht_user
  password: scht_password
  max_conn_attempts: 3
  failed_conn_delay: 5 # seconds
redis:
  host: 127.0.0.1
  port: 6380
  username: default
  password: ""
  max_conn_attempts: 3
  failed_conn_delay: 5 # seconds
logging:
  level: debug
  filepath: ./logs/all.log
  rotate: true
  max_size: 100   # MB
  max_backups: 5  # max files
cors:
  allowed_origins:
    - 127.0.0.1:3000
    - localhost:3000
  max_age: 600 # 10 minutes