name: Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}